server.port: 8765
spring:
  datasource:
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        default_schema: public

spring:
  application.name: winecellar
  profiles.active: server
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        format_sql : true
  mvc.favicon.enabled: false

flyway.enabled: false

management.security.enabled: false
